### ISSUE TITLE
Warbreaker Table of Contents has an ordering mistake

### ISSUE THREAD

**Issue by LewsTherinTelescope** [guusj/books#2]
While the content of the book is in the correct order if you scroll through and so is the in-text Table of Contents, if you look at the EPUB ToC the Epilogue is listed as the second chapter right after the Prologue, and Acknowledgments is third when it should actually be first. 

I haven't checked the MOBI etc files to verify whether the issue is present there or not.

**Comment by guusj** [comment]
Hello LewsTherinTelescope,

I can reproduce the issue using http://epub-reader.online.
At first sight this looks like a Calibre conversion error. I used a rather old Calibre version so a newer version may very well be better.

Unfortunately I will not fix this issue. Essentially this project was meant as a one-time PDF-to-markdown conversion. The inclusion of the easier markdown-to-epub/mobi conversion is a bonus but can and maybe should be optimized by anybody as mentioned in eg README.md.

The only other issue report mentioned a text improvement made by Brandon Sanderson and it made sense to update "my" version as well.

Just a happy thought to end this disappointing answer:
The Wheel turns and Ages come and pass. It's up to you to make the epub first class.
